---
# tasks file for stunnel
- name: Install stunnel
  yum: name={{ item }} state=installed
  with_items:
    - stunnel
    - openssl-devel
  tags:
    - packages

- name: Makesure config dir
  file: path=/etc/stunnel state=directory
  tags:
    - packages

- name: Copy init script
  copy: src="files/stunnel.init"  dest="/etc/init.d/stunnel"  mode=0755
  tags:
    - update

- name: Copy pem files
  copy: src="files/stunnel.pem"  dest="/etc/stunnel/stunnel.pem"  mode=0644
  tags:
    - update

- name: Update config
  template: src=templates/etc/stunnel/stunnel.conf.j2 dest=/etc/stunnel/stunnel.conf
  tags:
    - update
