---
- name: Install squid from yum
  yum: name=squid state=latest

- name: Create facts directory
  file: path=/etc/ansible/facts.d state=directory

- name: Enable squid service
  service: name=squid enabled=yes

- name: Install squid fact
  copy: content="{{ squid }}" dest=/etc/ansible/facts.d/squid.fact
